---
title: "Mark for Exam"
output: html_document
date: "2023-10-19"
---

```{r}
#Part E
# Use the Quantile Method to obtain the critical value for the multivar Poisson
# goal is to get a critical region size alpha = 0.05
lower<-qpois(0.025,lambda = 10)
upper<-qpois(0.975, lambda = 10)
crit_vals<- c(lower,upper)
print(paste("critical values: ", lower, upper))
crit_reg_size<-ppois(lower, 10)+(1-ppois(upper,10))
print(paste("critical region size", crit_reg_size))


```
```{r}
#Part F
simulation_num <- 10000
in_crit_region <- 0
for (i in 1:simulation_num) {
  dist <- rpois(10, lambda = 1)
  test_stat <- sum(dist)
  lower_critical_value <- qpois(0.025, lambda = 10)
  upper_critical_value <- qpois(0.975, lambda = 10)
  if (test_stat < lower_critical_value || test_stat > upper_critical_value) {
    in_crit_region <- in_crit_region + 1
  }
}
proportion <- in_crit_region / simulation_num
proportion

```
```{r}
#Part G
simulation_num <- 10000
in_crit_region2 <- 0
for (i in 1:simulation_num) {
  dist2 <- rpois(10, lambda = 2)
  test_stat2 <- sum(dist2)
  lower_critical_value <- qpois(0.025, lambda = 10)
  upper_critical_value <- qpois(0.975, lambda = 10)
  if (test_stat2 < lower_critical_value || test_stat2 > upper_critical_value) {
    in_crit_region2 <- in_crit_region2 + 1
  }
}
proportion <- in_crit_region2 / simulation_num
proportion
```

